### ISSUE TITLE
ImportError when installed with pipx

### ISSUE THREAD

**Issue by mmwinther** [statisticsnorway/dapla-team-cli#269]
## Reproduction steps

```
pipx install dapla-team-cli
dpteam --version
```

## Install details

```
  installed package dapla-team-cli 0.1.2, installed using Python 3.11.2
  These apps are now globally available
    - dpteam
done! ✨ 🌟 ✨
```

## Traceback

```
Traceback (most recent call last):
  File "/Users/mmwinther/.local/bin/dpteam", line 5, in <module>
    from dapla_team_cli.__main__ import main
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/dapla_team_cli/__main__.py", line 23, in <module>
    import dapla_team_cli.auth.cmd as auth
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/dapla_team_cli/auth/cmd.py", line 13, in <module>
    from dapla_team_cli.auth.services.get_token import get_token
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/dapla_team_cli/auth/services/get_token.py", line 9, in <module>
    from jupyterhub.services.auth import HubAuth
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/jupyterhub/services/auth.py", line 59, in <module>
    from ..scopes import _intersect_expanded_scopes
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/jupyterhub/scopes.py", line 30, in <module>
    from . import orm, roles
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/jupyterhub/orm.py", line 9, in <module>
    import alembic.command
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/runtime/environment.py", line 15, in <module>
    from .migration import _ProxyTransaction
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/runtime/migration.py", line 30, in <module>
    from .. import ddl
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/ddl/mssql.py", line 17, in <module>
    from .base import AddColumn
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/ddl/base.py", line 16, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/util/__init__.py", line 16, in <module>
    from .messaging import err
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/util/messaging.py", line 16, in <module>
    from . import sqla_compat
  File "/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/alembic/util/sqla_compat.py", line 115, in <module>
    from sqlalchemy.sql.base import _NoneName
ImportError: cannot import name '_NoneName' from 'sqlalchemy.sql.base' (/Users/mmwinther/.local/pipx/venvs/dapla-team-cli/lib/python3.11/site-packages/sqlalchemy/sql/base.py)
```

**Comment by nicolst** [comment]
Solved with @damirmedakovic and @mallport, sqlalchemy dependency needs to be set to ^1.4.47. Something in >=2.0.0 breaks it
